// @CAIMEOX
// Interrupt Vectors (Extracts from STC32 Lib)
// JS Code: text.split('\n').map(x=>x.split(' ').filter(x=>x.length!=0)).map(x=>x[0]+' '+x[1]).join('\n')

#define INT0_VECTOR
#define TMR0_VECTOR
#define INT1_VECTOR
#define TMR1_VECTOR
#define UART1_VECTOR
#define ADC_VECTOR
#define LVD_VECTOR
#define PCA_VECTOR
#define UART2_VECTOR
#define SPI_VECTOR
#define INT2_VECTOR
#define INT3_VECTOR
#define TMR2_VECTOR
#define USER_VECTOR
#define INT4_VECTOR
#define UART3_VECTOR
#define UART4_VECTOR
#define TMR3_VECTOR
#define TMR4_VECTOR
#define CMP_VECTOR
#define I2C_VECTOR
#define USB_VECTOR
#define PWMA_VECTOR
#define PWMB_VECTOR
#define CAN_VECTOR
#define CAN2_VECTOR
#define LIN_VECTOR
#define RTC_VECTOR
#define P0INT_VECTOR
#define P1INT_VECTOR
#define P2INT_VECTOR
#define P3INT_VECTOR
#define P4INT_VECTOR
#define P5INT_VECTOR
#define P6INT_VECTOR
#define P7INT_VECTOR
#define M2MDMA_VECTOR
#define ADCDMA_VECTOR
#define SPIDMA_VECTOR
#define U1TXDMA_VECTOR
#define U1RXDMA_VECTOR
#define U2TXDMA_VECTOR
#define U2RXDMA_VECTOR
#define U3TXDMA_VECTOR
#define U3RXDMA_VECTOR
#define U4TXDMA_VECTOR
#define U4RXDMA_VECTOR
#define LCMDMA_VECTOR
#define LCM_VECTOR
#define I2CTXDMA_VECTOR
#define I2CRXDMA_VECTOR
#define I2S_VECTOR
#define I2STXDMA_VECTOR
#define I2SRXDMA_VECTOR